### ISSUE TITLE
In the plugin directory, there is a prompt that the following file realsrgan x4. onnx cannot be found, and it is also not available on the hanging face

### ISSUE THREAD

**Issue by einstein33** [jtydhr88/ComfyUI-Unique3D#12]
*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using [('TensorrtExecutionProvider', {'device_id': 0, 'trt_max_workspace_size': 8589934592, 'trt_fp16_enable': True, 'trt_engine_cache_enable': True}), ('CUDAExecutionProvider', {'device_id': 0, 'arena_extend_strategy': 'kSameAsRequested', 'gpu_mem_limit': 8589934592, 'cudnn_conv_algo_search': 'HEURISTIC'})]
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
!!! Exception during processing!!! [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\AI\comfyui-3d/custom_nodes/ComfyUI-Unique3D/ckpt/realesrgan-x4.onnx failed:Load model C:\AI\comfyui-3d/custom_nodes/ComfyUI-Unique3D/ckpt/realesrgan-x4.onnx failed. File doesn't exist
Traceback (most recent call last):
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 469, in _create_inference_session
    self._register_ep_custom_ops(session_options, providers, provider_options, available_providers)
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 516, in _register_ep_custom_ops
    C.register_tensorrt_plugins_as_custom_ops(session_options, provider_options[i])
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\AI\comfyui-3d\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\custom_nodes\ComfyUI-Unique3D\run.py", line 97, in run
    preview_img = run_sr_fast([preview_img])[0]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\custom_nodes\ComfyUI-Unique3D\scripts\refine_lr_to_sr.py", line 43, in run_sr_fast
    upsampler = RealESRGANer(
                ^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d/custom_nodes/ComfyUI-Unique3D\scripts\upsampler.py", line 48, in __init__
    self.model = load_onnx_caller(onnx_path, single_output=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d/custom_nodes/ComfyUI-Unique3D\scripts\load_onnx.py", line 27, in load_onnx_caller
    ort_session = load_onnx(file_path)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d/custom_nodes/ComfyUI-Unique3D\scripts\load_onnx.py", line 22, in load_onnx
    ort_session = onnxruntime.InferenceSession(file_path, sess_opt=sess_opt, providers=providers)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\AI\comfyui-3d/custom_nodes/ComfyUI-Unique3D/ckpt/realesrgan-x4.onnx failed:Load model C:\AI\comfyui-3d/custom_nodes/ComfyUI-Unique3D/ckpt/realesrgan-x4.onnx failed. File doesn't exist

**Comment by yosun** [comment]
install  the model using comfyui manager

**Comment by einstein33** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到，我将尽快给您回复。

**Comment by jtydhr88** [comment]
@einstein33 请提供你系统的环境。
目前来看你在安装onnxruntime的时候装错了版本，如果你是cuda12.1，你不能直接pip install onnxruntime，这个方式安装版本是针对cuda 11.8的，具体参见我在这里的留言：https://github.com/AiuniAI/Unique3D/issues/35。
同时，如果你用的不是从ComfyUI Github release页面里下载，你的目录结构不是我提供的bat期待，你需要根据我的bat里面的步骤自己配一下

**Comment by jtydhr88** [comment]
since no more information comes, I would like to close issue this for now, please feel free to reopen if you still need it
