### ISSUE TITLE
I reinstalled the ComfyUI Unique3D node and when running, it prompted NotImplementedError: auto not supported Supported strategies are: balanced errors, how can this be resolved

### ISSUE THREAD

**Issue by einstein33** [jtydhr88/ComfyUI-Unique3D#15]
Traceback (most recent call last):
  File "C:\AI\comfyui-3d\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\custom_nodes\ComfyUI-Unique3D\run.py", line 62, in run
    pipe = load_common_sd15_pipe(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 107, in load_common_sd15_pipe
    pipe: StableDiffusionPipeline = model_from_ckpt_or_pretrained(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\comfyui-3d\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 44, in model_from_ckpt_or_pretrained
    pipe = model_cls.from_pretrained(ckpt_or_pretrained, torch_dtype=torch_dtype, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\einstein\.conda\envs\cf3d\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 680, in from_pretrained
    raise NotImplementedError(
NotImplementedError: auto not supported. Supported strategies are: balanced

**Comment by jtydhr88** [comment]
this is because you installed unsupport diffuser, you need to uninstall it then re-install, see https://github.com/jtydhr88/ComfyUI-Unique3D/issues/13
