### ISSUE TITLE
3d pack conflicts with unique3d

### ISSUE THREAD

**Issue by MingYuZhuang** [jtydhr88/ComfyUI-Unique3D#19]
After installing 3d pack, the production model can run normally. After installing unique 3d, the node reports an error and prompts the following log.
(env pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121

Log
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-15 12:01:03.566499
** Platform: Windows
** Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
** Python executable: D:\Unique3D\manage\python_embeded\python.exe
** ComfyUI Path: D:\Unique3D\manage\ComfyUI
** Log path: D:\Unique3D\manage\comfyui.log

Prestartup times for custom nodes:
   0.8 seconds: D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65277 MB
pytorch version: 2.3.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 718, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 23, in <module>
    from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\models\autoencoders\vae.py", line 24, in <module>
    from ..attention_processor import SpatialNorm
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\models\attention_processor.py", line 34, in <module>
    import xformers.ops
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\ops\__init__.py", line 8, in <module>
    from .fmha import (
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\ops\fmha\__init__.py", line 10, in <module>
    from . import (
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\ops\fmha\triton_splitk.py", line 54, in <module>
    if TYPE_CHECKING or _has_triton21():
                        ^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\ops\common.py", line 185, in _has_triton21
    if not _is_triton_available():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\__init__.py", line 38, in func_wrapper
    value = func()
            ^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\triton\__init__.py", line 12, in <module>
    from .dropout import FusedDropoutBias, dropout  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\xformers\triton\dropout.py", line 13, in <module>
    import triton
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune, heuristics)
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\runtime\autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\language\__init__.py", line 6, in <module>
    from .standard import (
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\language\standard.py", line 3, in <module>
    from ..runtime.jit import jit
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 10, in <module>
    from ..runtime.driver import driver
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 44, in _discover_backends
    driver = _load_module(name, os.path.join(root, name, 'driver.py'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 18, in <module>
    library_dir += [os.path.join(os.environ.get("CUDA_PATH"), "lib", "x64")]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 108, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 718, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 44, in <module>
    from ..models import AutoencoderKL
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 708, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 720, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Unique3D\manage\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 18, in <module>
    from diffusers import (
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 709, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 708, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 720, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType

Cannot import D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType
### ComfyUI Revision: 2364 [7914c47d] | Released on '2024-07-14'
python_executable_path:  D:\Unique3D\manage\python_embeded\python.exe
python_embeded_path:  D:\Unique3D\manage\python_embeded

Import times for custom nodes:
   0.0 seconds: D:\Unique3D\manage\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-Unique3D
   0.2 seconds (IMPORT FAILED): D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   0.2 seconds: D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by MingYuZhuang** [comment]
I reinstalled torch and solved this problem, but when I ran it.

got prompt
PyTorch version 2.3.0+cu121 available.
Warning! extra parameter in cli is not verified, may cause erros.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00, 92.59it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2mvimg.StableDiffusionImage2MVCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
RGB image not RGBA! still remove bg!
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]Warning! condition_latents is not None, but self_attn_ref is not enabled! This warning will only be raised once.
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 27.30it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:01<00:00,  4.87it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
!!! Exception during processing!!! auto not supported. Supported strategies are: balanced
Traceback (most recent call last):
  File "D:\Unique3D\manage\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-Unique3D\run.py", line 68, in run
    pipe = load_common_sd15_pipe(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 107, in load_common_sd15_pipe
    pipe: StableDiffusionPipeline = model_from_ckpt_or_pretrained(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\ComfyUI\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 44, in model_from_ckpt_or_pretrained
    pipe = model_cls.from_pretrained(ckpt_or_pretrained, torch_dtype=torch_dtype, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\manage\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 680, in from_pretrained
    raise NotImplementedError(
NotImplementedError: auto not supported. Supported strategies are: balanced

Prompt executed in 141.05 seconds

**Comment by jtydhr88** [comment]
(Due the latest diffusers is not compatible to the code of repo, we MUST install this for diffusers manually) pip install diffusers==0.27.2

**Comment by GBLKai** [comment]
Reinstalling Torch reminded me,
In my case, I installed xformers.
After uninstalling, the error doesn't seem to appear.
