### ISSUE TITLE
Request: Please add steps for setup on an Ubuntu Server

### ISSUE THREAD

**Issue by v4r4rth** [jtydhr88/ComfyUI-Unique3D#3]
Thanks for your hard work, looking forward to trying this amazing new model and method - I am unable to setup the Unique-3D part of the process though, the 3D-Pack is installed correctly!

Can you please provide steps to setup on an Ubuntu server? Thanks in advance! :)

**Comment by v4r4rth** [comment]
I am getting this error on startup - 
```
Traceback (most recent call last):
  File "/home/sid/ComfyUI/nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/__init__.py", line 1, in <module>
    from .run import NODE_CLASS_MAPPINGS
  File "/home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/run.py", line 21, in <module>
    from .app.custom_models.mvimg_prediction import run_mvprediction
  File "/home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/app/custom_models/mvimg_prediction.py", line 24, in <module>
    trainer, pipeline = load_pipeline(training_config, checkpoint_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/app/custom_models/utils.py", line 56, in load_pipeline
    trainers, configurable_unet = init_trainers(training_config, weight_dtype, extras)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/app/custom_models/utils.py", line 21, in init_trainers
    configurable_unet = ConfigurableUNet2DConditionModel(init_config, weight_dtype)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/custum_3d_diffusion/custum_modules/unifield_processor.py", line 142, in __init__
    self.set_config(init_config)
  File "/home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/custum_3d_diffusion/custum_modules/unifield_processor.py", line 205, in set_config
    self.unet: UnifieldWrappedUNet = unet_type.from_pretrained(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/.conda/envs/comfyui/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sid/.conda/envs/comfyui/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 567, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "/home/sid/.conda/envs/comfyui/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sid/.conda/envs/comfyui/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like #YOUR_COMFYUI_PATH#/custom_nodes/ComfyUI-Unique3D/ckpt/img2mvimg is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
```

**Comment by jtydhr88** [comment]
Hi, Linux support still is WIP.
But for your error, likely you don't put ckpt folder in the repo

**Comment by jtydhr88** [comment]
![image](https://github.com/jtydhr88/ComfyUI-Unique3D/assets/860985/6ef2ed85-92f5-451a-913e-173b98a06282)

**Comment by jtydhr88** [comment]
Download the weights from [huggingface spaces](https://huggingface.co/spaces/Wuvin/Unique3D/tree/main/ckpt) or [Tsinghua Cloud Drive](https://cloud.tsinghua.edu.cn/d/319762ec478d46c8bdf7/), and extract it to ckpt/*.

**Comment by v4r4rth** [comment]
I used the huggingface cli with this line - 

```
huggingface-cli download Wuvin/Unique3D --repo-type space --local-dir /home/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D/ckpt
```

Then simply copied over the ckpt files to the right directory

The import failed notification is still present

![image](https://github.com/jtydhr88/ComfyUI-Unique3D/assets/149033251/77edbf46-1a9b-4bd9-b51b-ba1bb097c4e1)

**Comment by jtydhr88** [comment]
just want to double check, have you done this step?
`go to ComfyUI-Unique3D/app/custom_models, and open image2normal.yaml, change replace the #YOUR_COMFYUI_PATH# in the first line with your ComfyUI absolute path
`

**Comment by v4r4rth** [comment]
I'm sorry but do I just paste the path into the top line? What must the syntax look like? The image2normal.yaml does not have anything specifc to edit but I have added the path in the image2mvimage.yaml file as the #YOUR_COMFYUI_PATH# was present there...

**Comment by jtydhr88** [comment]
please refer to this issue https://github.com/jtydhr88/ComfyUI-Unique3D/issues/4, looks like it is the same as yours

**Comment by v4r4rth** [comment]
Thank you, the .yaml change made sure the pack could get loaded - no more IMPORT FAILED and yes to HQ 3D :D
