### ISSUE TITLE
ModuleNotFoundError: import of wandb halted; None in sys.modules

### ISSUE THREAD

**Issue by pzc163** [jtydhr88/ComfyUI-Unique3D#8]
OS：win11
Cuda:12.1
torch:2.2.2
tensorRT：10.0.16
wandb:0.17.3

PyTorch version 2.2.2+cu121 available.
!!! Exception during processing!!! import of wandb halted; None in sys.modules
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\run.py", line 101, in run
    from .app.custom_models.mvimg_prediction import run_mvprediction
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\app\custom_models\mvimg_prediction.py", line 21, in <module>
    from ..custom_models.utils import load_pipeline
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\app\custom_models\utils.py", line 6, in <module>
    from custum_3d_diffusion import modules
  File "E:\ComfyUI-aki-v1.3/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\modules.py", line 14, in <module>
    from custum_3d_diffusion.trainings import base, image2mvimage_trainer, image2image_trainer
  File "E:\ComfyUI-aki-v1.3/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\trainings\base.py", line 11, in <module>
    import wandb
ModuleNotFoundError: import of wandb halted; None in sys.modules

done anyone know how to solve it？

**Comment by jtydhr88** [comment]
Hi, please provide me the steps you set up env.
I only test the bundle downloaded from ComfyUI GitHub release page with the embedded python.

**Comment by yemaozi9** [comment]
Prompt executed in 77.14 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! import of wandb halted; None in sys.modules
Traceback (most recent call last):
  File "D:\AI_tools\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_tools\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_tools\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\run.py", line 101, in run
    from .app.custom_models.mvimg_prediction import run_mvprediction
  File "D:\AI_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\app\custom_models\mvimg_prediction.py", line 21, in <module>
    from ..custom_models.utils import load_pipeline
  File "D:\AI_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\app\custom_models\utils.py", line 6, in <module>
    from custum_3d_diffusion import modules
  File "D:\AI_tools\ComfyUI-aki-v1.3/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\modules.py", line 14, in <module>
    from custum_3d_diffusion.trainings import base, image2mvimage_trainer, image2image_trainer
  File "D:\AI_tools\ComfyUI-aki-v1.3/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\trainings\base.py", line 11, in <module>
    import wandb
ModuleNotFoundError: import of wandb halted; None in sys.modules

Prompt executed in 37.51 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! import of wandb halted; None in sys.modules

**Comment by jtydhr88** [comment]
sorry, but looks likely your environment is quite different from mine, and just I mentioned in Readme, it is highly recommended to use a fresh new bundle downloaded from ComfyUI GitHub release page here https://github.com/comfyanonymous/ComfyUI/releases and keep the folder structure as default, this is what I tested on my end.

**Comment by pzc163** [comment]
I'm using a comfyUI launcher from Chinese developer Qiuye, python version is 3.10. I installed all the requirements manually in a python environment following your readme, except for the python version 3.10. I followed your installation instructions!

**Comment by pzc163** [comment]
> Prompt executed in 77.14 seconds got prompt [rgthree] Using rgthree's optimized recursive execution. !!! Exception during processing!!! import of wandb halted; None in sys.modules Traceback (most recent call last): File "D:\AI_tools\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\AI_tools\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\AI_tools\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\AI_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\run.py", line 101, in run from .app.custom_models.mvimg_prediction import run_mvprediction File "D:\AI_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\app\custom_models\mvimg_prediction.py", line 21, in from ..custom_models.utils import load_pipeline File "D:\AI_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Unique3D\app\custom_models\utils.py", line 6, in from custum_3d_diffusion import modules File "D:\AI_tools\ComfyUI-aki-v1.3/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\modules.py", line 14, in from custum_3d_diffusion.trainings import base, image2mvimage_trainer, image2image_trainer File "D:\AI_tools\ComfyUI-aki-v1.3/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\trainings\base.py", line 11, in import wandb ModuleNotFoundError: import of wandb halted; None in sys.modules
> 
> Prompt executed in 37.51 seconds got prompt [rgthree] Using rgthree's optimized recursive execution. !!! Exception during processing!!! import of wandb halted; None in sys.modules

it seems occur same error as me！ I think it maybe the wandb version is not suitable for the Unique 3D nodes

**Comment by pzc163** [comment]
感觉秋叶启动器和这个项目不兼容，只要使用秋叶来安装这个项目都无法成功启动

**Comment by jtydhr88** [comment]
应该是的，我自己没有使用任何的启动器

**Comment by pzc163** [comment]
> 应该是的，我自己没有使用任何的启动器

我今天照着您写的步骤，在秋叶启动器的python环境中操作了一遍，还是卡在了wandb的报错上，是不是这个库的版本问题，不兼容？其他问题都已经解决了

**Comment by jtydhr88** [comment]
我这周找时间在秋叶里试一下吧

**Comment by jtydhr88** [comment]
问一下秋叶启动器的官方下载地址是什么？我搜了一圈全都是转载网盘的，不像是官方地址

**Comment by pzc163** [comment]
> 问一下秋叶启动器的官方下载地址是什么？我搜了一圈全都是转载网盘的，不像是官方地址

没有什么官方下载地址，大家都是从B站上UP主秋叶的页面给的网盘链接下载的

**Comment by pzc163** [comment]
> 问一下秋叶启动器的官方下载地址是什么？我搜了一圈全都是转载网盘的，不像是官方地址

秋叶启动器夸克网盘【下载链接】
网盘：https://pan.quark.cn/s/64b808baa960
百度网盘链接：
https://pan.baidu.com/share/init?surl=9aektdzDcnkLdQhEtDJTJA
提取码:aaki

**Comment by LianTianNo1** [comment]
Encountered the same error, using qiuye integration package, python3.10,win11, cu121

**Comment by yogurt7771** [comment]
可以把import wandb这句话移到下面用它的地方
ComfyUI\custom_nodes\ComfyUI-Unique3D\custum_3d_diffusion\trainings\base.py
删除11行的import wandb
在161行，elif tracker.name == "wandb":的下面加一个import wandb就行了

**Comment by jtydhr88** [comment]
@yogurt7771 感谢，已更新代码

**Comment by wfjsw** [comment]
`wandb` was selectively blocked on some installations because it is one of the main causes of the pb2 issue when the `tensorflow` and `google-protobuf` versions disagree. `jax`, `jaxlib` and `tensorboard` are all blocked for similar reason.

I don't quite understand why this project requires wandb. Does this project involves training?

**Comment by jtydhr88** [comment]
@wfjsw thanks for sharing, this part comes from the original implementation https://github.com/AiuniAI/Unique3D, could you share your thoughts in this original repo?

**Comment by wfjsw** [comment]
A brief look shows that wandb is absolutely not necessary. The custom models does not implement validation and in turns `do_validations` is not called in the process.

**Comment by thefirstLeonliao** [comment]
> 我这周找时间在秋叶里试一下吧

怎么样了大佬

**Comment by wfjsw** [comment]
> I was thinking about reducing the scope of this mitigation, but the original error report was purged from the stash and I can't find a more recent one.
> 
> A patch was shipped with Launcher version 2.8.5 Build 347 that temporarily disabled this mitigation, until I get more information to refine it. As a result, you should no longer experience this error.

_Originally posted in https://github.com/2kpr/ComfyUI-UltraPixel/issues/12#issuecomment-2241047502_
